### ISSUE TITLE
pip install seems broken

### ISSUE THREAD

**Issue by rustybrooks** [keithjjones/visualize_logs#1]
Hi,

Tried to pip-install just now, and got this error

~~~~
(venv) RBROOKS-MBPTE:visualize_logs rustybrooks$ pip install visualize_logs
Collecting visualize_logs
  Downloading visualize_logs-20161112.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f5/6k6f6t290pdb329nn8gb4yd80000gp/T/pip-build-I36Oqt/visualize-logs/setup.py", line 23, in <module>
        long_description=read('README.TXT'),
      File "/private/var/folders/f5/6k6f6t290pdb329nn8gb4yd80000gp/T/pip-build-I36Oqt/visualize-logs/setup.py", line 10, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/private/var/folders/f5/6k6f6t290pdb329nn8gb4yd80000gp/T/pip-build-I36Oqt/visualize-logs/README.TXT'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/f5/6k6f6t290pdb329nn8gb4yd80000gp/T/pip-build-I36Oqt/visualize-logs/
~~~~

**Comment by keithjjones** [comment]
Thanks for reporting.  That's odd, README.TXT is in there.  You can always checkout the repository and pip install from that.  I don't think I'll have time to fix this anytime soon.  If you find the problem and fix it, I'll accept the pull request.  Thanks!

**Comment by rustybrooks** [comment]
OK, no problem, I'm actually just running the setup.py myself locally.  Just happened to notice and thought I'd let you know.

**Comment by keithjjones** [comment]
I do appreciate it.  Take a look at this pull request for one of my other repositories.  See if that is teh same issue you are experiencing here?  What file system are you using?

https://github.com/keithjjones/cuckoo-api/pull/1

**Comment by rustybrooks** [comment]
I experienced it both with OSX and linux - I don't think it's a file case issue.

I can see the file in the repo and it's where I'd expect it, so I guess I'd be suspicious of a python "egg" issue of some kind. I have little experience either with eggs or pip installs though.

**Comment by keithjjones** [comment]
It installs fine for me:

```
(Python3) Keiths-MacBook-Pro:visualize_logs keithjones$ pip install visualize_logs
Collecting visualize_logs
  Downloading visualize_logs-20161112.2-py3-none-any.whl
Collecting networkx (from visualize_logs)
  Downloading networkx-2.0.zip (1.5MB)
    100% |████████████████████████████████| 1.6MB 909kB/s 
Collecting pydotplus (from visualize_logs)
  Downloading pydotplus-2.0.2.tar.gz (278kB)
    100% |████████████████████████████████| 286kB 3.6MB/s 
Requirement already satisfied: plotly>=1.9.0 in /Users/keithjones/.virtualenvs/Python3/lib/python3.5/site-packages (from visualize_logs)
Collecting pandas (from visualize_logs)
  Downloading pandas-0.20.3-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (14.7MB)
    100% |████████████████████████████████| 14.7MB 93kB/s 
Collecting decorator>=4.1.0 (from networkx->visualize_logs)
  Downloading decorator-4.1.2-py2.py3-none-any.whl
Collecting pyparsing>=2.0.1 (from pydotplus->visualize_logs)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 8.6MB/s 
Requirement already satisfied: nbformat>=4.2 in /Users/keithjones/.virtualenvs/Python3/lib/python3.5/site-packages (from plotly>=1.9.0->visualize_logs)
Requirement already satisfied: requests in /Users/keithjones/.virtualenvs/Python3/lib/python3.5/site-packages (from plotly>=1.9.0->visualize_logs)
Requirement already satisfied: six in /Users/keithjones/.virtualenvs/Python3/lib/python3.5/site-packages (from plotly>=1.9.0->visualize_logs)
Requirement already satisfied: pytz in /Users/keithjones/.virtualenvs/Python3/lib/python3.5/site-packages (from plotly>=1.9.0->visualize_logs)
Collecting python-dateutil>=2 (from pandas->visualize_logs)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 4.9MB/s 
Requirement already satisfied: numpy>=1.7.0 in /Users/keithjones/.virtualenvs/Python3/lib/python3.5/site-packages (from pandas->visualize_logs)
Requirement already satisfied: jupyter-core in /Users/keithjones/.virtualenvs/Python3/lib/python3.5/site-packages (from nbformat>=4.2->plotly>=1.9.0->visualize_logs)
Requirement already satisfied: ipython-genutils in /Users/keithjones/.virtualenvs/Python3/lib/python3.5/site-packages (from nbformat>=4.2->plotly>=1.9.0->visualize_logs)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/keithjones/.virtualenvs/Python3/lib/python3.5/site-packages (from nbformat>=4.2->plotly>=1.9.0->visualize_logs)
Requirement already satisfied: traitlets>=4.1 in /Users/keithjones/.virtualenvs/Python3/lib/python3.5/site-packages (from nbformat>=4.2->plotly>=1.9.0->visualize_logs)
Building wheels for collected packages: networkx, pydotplus
  Running setup.py bdist_wheel for networkx ... done
  Stored in directory: /Users/keithjones/Library/Caches/pip/wheels/27/82/23/785d5d01de2271edf929ac2761cb5dafc0dfa76a0861bfd128
  Running setup.py bdist_wheel for pydotplus ... done
  Stored in directory: /Users/keithjones/Library/Caches/pip/wheels/43/31/48/e1d60511537b50a8ec28b130566d2fbbe4ac302b0def4baa48
Successfully built networkx pydotplus
Installing collected packages: decorator, networkx, pyparsing, pydotplus, python-dateutil, pandas, visualize-logs
  Found existing installation: decorator 4.0.11
    Uninstalling decorator-4.0.11:
      Successfully uninstalled decorator-4.0.11
Successfully installed decorator-4.1.2 networkx-2.0 pandas-0.20.3 pydotplus-2.0.2 pyparsing-2.2.0 python-dateutil-2.6.1 visualize-logs-20161112.2
(Python3) Keiths-MacBook-Pro:visualize_logs keithjones$ 
```
Are you using Python2 or Python3?  It won't work with Python2.

**Comment by keithjjones** [comment]
That was on my OSX machine with Python3 in virtualenv.

**Comment by rustybrooks** [comment]
I just tried it and it did work for me - I'm using python 2.  I don't have
time to fiddle with it now but trying to run it in python 2 does not
succeed for me, I get an error with some datetime format stuff.  As you
say, I guess it's not supposed to work in python 2.

I should have some time tomorrow or maybe this afternoon to try it in a
python 3 virtualenv, but since the rest of our stack is python 2.7, that
might not end up working out so great.  But frankly, mostly at this point
I'm looking at visualization ideas anyway, rather than straight out plug
and play solutions.

**Comment by keithjjones** [comment]
Sounds good.
